services:
  frontend:
    build: ./frontend
    container_name: weatherapp_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 8000:8000
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./frontend/.env

  backend:
    build: ./backend
    container_name: weatherapp_backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 9000:9000
    env_file:
      - ./backend/.env
